### ISSUE TITLE
Not working in non-English locales

### ISSUE THREAD

**Issue by pato-yapoq** [cyberang3l/kdeconnect-sms#2]
Hej,

takk for the script, I find it really useful.
It took me a while to make it work, before I realized that it would only work with English:

```
The device with id dd6c8cd874e0b556 is either not paired or not not reachable.
Here is a list of all kdeconnect-cli paired devices (not necessarily reachable):
- Lenovo: dd6c8cd874e0b556 (spárovaná a dosažitelná)
Nalezeno 1 zařízení
```

because it looks for "paired and reachable":

`if ! kdeconnect-cli -l | grep "${phoneIdToUse}" | grep "paired and reachable" 2>&1 > /dev/null;`

I am not sure whether it can be modified, but perhaps an info could be put in the readme...
I just changed it to:

`if ! kdeconnect-cli -l | grep "${phoneIdToUse}" | grep "spárovaná a dosažitelná" 2>&1 > /dev/null;`

(I also added `echo -e "\tMessage sent\n"` at the end of the script... but it is rather because it took me some time to get it work.)

Thanks,
Pato

**Comment by cyberang3l** [comment]
Hi and thank you for this bug report.

I just pushed some changes. Can you try the latest version? I see that `kdeconnect-cli` now has a --list-available option that lists only the paired and reachable devices. This eliminates the need to have to grep for some locale-specific text.

**Comment by pato-yapoq** [comment]
Hej,

takk for the amend, it works fine, good way to fix it :+1: 
Btw., is it possible to make the autocompletion of phone numbers work also after the short option? It only works with `kdeconnect-sms --send-sms X`, but not with `kdeconnect-sms -s X`.

**Comment by cyberang3l** [comment]
Should be working now. You can also rename the command from kdeconnect-sms to whatever you like if you don't want much typing. I typically go for just `sms` as it is shorter and unique in a sense that there is no other command with the `sms` prefix in my system. Check the updated README.

**Comment by pato-yapoq** [comment]
Takk, works fint :)
I did exactly the same regarding `sms`.

I also added some line breaks to the error message and an info after successful send to make the output more visible in the terminal:

```
if ! kdeconnect-cli --list-available | grep "${phoneIdToUse}" 2>&1 > /dev/null; then
	echo -e "\nThe device with id ${phoneIdToUse} is either not paired or not not reachable."
	echo -e "Here is a list of all kdeconnect-cli paired devices (not necessarily reachable):"
	kdeconnect-cli -l
	echo -e "\n"
	exit 1
fi

kdeconnect-cli --device "${phoneIdToUse}" --send-sms "${message}" --destination "${sendTo}"
echo -e "\tMessage sent\n"
```

And I also created the address book elsewhere and changed the path.

Tusen takk! I was going to create a simple script (like `sms <number> <text>`), but yours is just perfect!
