### ISSUE TITLE
zsh completions?

### ISSUE THREAD

**Issue by testbughub** [cyberang3l/kdeconnect-sms#4]
I was just wondering if you could add auto-completions for zsh?  
I tried adding it with `source <(kdeconnect-sms -b)` since zsh can  
apparently read bash auto-completions,  
but it just hangs when I press tab, and I have to Ctrl+C it.  

After reading a bit about zsh auto-completions my head wouldn't stop spinning.  
I hope you have some more knowledge about it :sweat_smile:

**Comment by testbughub** [comment]
I found a guide and managed to create a very simple auto-complete function.  
```
#compdef _kdeconnect-sms kdeconnect-sms

_kdeconnect-sms() {
    local -a commands
    commands=(
        '-a:Prints the address book nicely formatted.'
        '--address-book:Prints the address book nicely formatted.'
        '-b:Prints the code for bash-completion.'
        '--bash-completion:Prints the code for bash-completion.'
        '-s:The phone number to send the SMS to.'
        '--send-to:The phone number to send the SMS to.'
        '-h:Prints this help message'
        '--help:Prints this help message'
    )

    if (( CURRENT == 2 )); then
        _describe -t commands 'commands' commands
    fi

    return 0
}

_kdeconnect-sms
```

This is probably not how you're supposed to write them, but it works!  
The only thing I'm missing is the auto-complete for the address book numbers.

**Comment by cyberang3l** [comment]
Hey there, I have no clue how zsh auto-completions work, sorry :(

**Comment by testbughub** [comment]
Oh well, maybe I'll get around to learn how to do it myself some day.  
Thanks anyway!
